// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(PlanesDbContext))]
    partial class PlanesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("DomainObjects.PlaneBoard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlaneBoardNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaneType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlaneType", "PlaneBoardNo")
                        .IsUnique();

                    b.ToTable("PlaneBoards");
                });

            modelBuilder.Entity("DomainObjects.PlaneFlight", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FlightDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FlightNo")
                        .HasColumnType("INTEGER");

                    b.Property<short>("FlightSmena")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PilotName")
                        .HasColumnType("TEXT");

                    b.Property<long>("PlaneBoardId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlaneBoardId");

                    b.ToTable("PlaneFlights");
                });

            modelBuilder.Entity("DomainObjects.PlaneFlight", b =>
                {
                    b.HasOne("DomainObjects.PlaneBoard", "PlaneBoard")
                        .WithMany("Flights")
                        .HasForeignKey("PlaneBoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlaneBoard");
                });

            modelBuilder.Entity("DomainObjects.PlaneBoard", b =>
                {
                    b.Navigation("Flights");
                });
#pragma warning restore 612, 618
        }
    }
}
